### ISSUE TITLE
Android java sample for version 5.0.0

### ISSUE THREAD

**Issue by limamauricio** [RevenueCat/purchases-android#534]
I tried to access the sample using java, but I was redirected to a not found page. Is there in the team's planning to provide a sample using java, as was done in previous versions? Or will support for android apps that use java end?

**Comment by pangia** [comment]
yes. the docs are full of bad links and circular references. we need to get our migration to the new version completed asap. please help.

**Comment by joshdholtz** [comment]
@limamauricio Thanks for letting us know! We will remove the Java example link (for now) and add it back in when we get a new Java example up.

@pangia It would be great if you have any specific examples of links or circular references that are broken! We'd be happy to go fix them 💪 But if not, we can comb through the docs and find anything that isn't right but that might take a little bit 😇 

Appreciate both your feedback!

**Comment by Noiling** [comment]
All links [here](https://docs.revenuecat.com/docs/getting-started-1#section-configure-purchases) under "see in action" are broken.

**Comment by aboedo** [comment]
Thanks for reporting! I can confirm that the links are broken, we'll get those fixed this week. @beylmk or @vegaro any thoughts on what might be causing the compilation issues?

**Comment by beylmk** [comment]
Hey @Noiling can you elaborate on the compilation issues you're facing? 

Can you successfully complete a gradle sync after adding the purchases-android dependency? Our library does require Java 8.

**Comment by beylmk** [comment]
Ah, thanks for the details. You're right, our Quickstart docs for Java are out of date. Thanks for alerting us -- I'll work on getting those fixed now.

For the method you posted, you can instead use:
```        
Purchases.getSharedInstance().getOfferings(new ReceiveOfferingsCallback() {

            @Override
            public void onReceived(@NonNull Offerings offerings) {
                
            }

            @Override
            public void onError(@NonNull PurchasesError error) {
                /* Optional error handling */
            }
        });
```

**Comment by beylmk** [comment]
@Noiling All of the Java examples on that page should be updated now... please let me know if you run into any issues with them!

**Comment by Noiling** [comment]
Ok, than I will have to wait. But one last question, in your provided code, I cannot use "toPurchase" (unknown). Thanks again.

**Comment by beylmk** [comment]
The edits should be live -- were you not seeing them?

`toPurchase` would be the package that you'd like to purchase. I've updated the parameter name to be more clear. The packages available to purchase are returned in `getOfferings`, under the `offering.availablePackages` property.

**Comment by Noiling** [comment]
If I take a look under "Making a purchase" inside the docs, I still see the old code.

Also, I receive an error message for your purchase code (I added the purchase as you stated):

```
public void purchase(Package p1){

        Purchases.getSharedInstance().purchasePackage(this, p1, new PurchaseCallback() {
            @Override
            public void onCompleted(@NonNull StoreTransaction storeTransaction, @NonNull CustomerInfo customerInfo) {
                if (customerInfo.getEntitlements().get("extended premium").isActive()) {
                    // Unlock that great "pro" content
                }
            }

            @Override
            public void onError(@NonNull PurchasesError purchasesError, boolean b) {
                // No purchase
            }
        });
    }
```

Error says: Cannot resolve method 'purchasePackage(com.appentwicklungseevetal.combapu.purchase.revenueCat, com.revenuecat.purchases.Package, anonymous com.revenuecat.purchases.interfaces.PurchaseCallback)'

**Comment by Noiling** [comment]
Thank you, that solved my problem ;)

**Comment by taquitos** [comment]
Docs updated and problems solved! 🎉
